### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by GanerCodes** [ederwander/PyAutoTune#7] opened 2020-07-29 14:07 UTC
I've been at this for like 45 minutes and it just refuses to install, there's problems with both pyaudio and setup.py. Not to mention the .cfg file also makes it so pip doesn't work. And yes I got the old version of python (3.7) and that didn't work either. [Errors](https://i.imgur.com/6kFvKju.png)

**Comment by ederwander** [comment] 2020-07-29 15:47
This error is clear as water, If you have successfully installed numpy, point the path of the includes (include_dirs) in distutils.cfg :

Create one file distutils.cfg in your python distutils PATH instalation Ex:C:\Python37\Lib\distutils

[build]
compiler=mingw32


 [build_ext]
include_dirs= C:\Python37\Lib\site-packages\numpy\core\include


for Pyaudio maybe you can ckeck the official developer site, I just compile it using mingw and not ms visual studio ...

**Comment by GanerCodes** [comment] 2020-07-29 16:32
I had already done that 
![Image](https://user-images.githubusercontent.com/34655998/88827032-0d300200-d18f-11ea-9dfb-75ce4d90c78e.png)

**Comment by ederwander** [comment] 2020-07-29 18:39
Well if you install mingw, then why it is trying compile using visual studio ???  ...

you have set the path of mingw ?

if you keep trying to compile using ms visual studio the problem is in it, it is not being able to find the way to include numpy, define where to point the numpy includes path in your visual studio

**Comment by GanerCodes** [comment] 2020-07-29 19:41
I've hardly ever used C++/C so I'm not sure how to configure things, here is my path right now, what should I do? 
![gKLxV6P](https://user-images.githubusercontent.com/34655998/88845349-a10ec780-d1a9-11ea-84e3-556e4d741e2a.png)

**Comment by ederwander** [comment] 2020-07-29 20:01
you said you were trying to install on python37 right? I'm just seeing path to python38, remove the path from python38 and enter the path to python37

**Comment by GanerCodes** [comment] 2020-07-29 21:50
Did that, it unfortunately changed nothing. Also I don't think theres any significant differences between 37 and 38 to make a difference anyway, right?

**Comment by ederwander** [comment] 2020-07-29 22:04
> Did that, it unfortunately changed nothing. Also I don't think theres any significant differences between 37 and 38 that would affect anything, right?

**Comment by ederwander** [comment] 2020-07-29 22:09
you need to find out why your python is calling ms visual studio and not the minGW, i heved compiled this in different machines but all machines are using python37, when you call python setup.py install he needs to call the minGW that you configured in the distutils folder... it's like your python settings are ignoring the distutils.cfg parameters

**Comment by ederwander** [comment] 2020-07-29 22:38
one more thing try force the install using:

python.exe setup.py install build --compiler=mingw32

**Comment by GanerCodes** [comment] 2020-07-29 23:44
![IfLYU3f](https://user-images.githubusercontent.com/34655998/88864750-7cc3e280-d1cb-11ea-9ca9-c4e299b8467b.png)

**Comment by ederwander** [comment] 2020-07-30 00:14
in the file` cygwinccompiler.py` here it is in `C:\Python37\Lib\distutils`

find the line `if msc_pos != -1:` and add ms compiler version 1916

```
elif msc_ver == "1916":
     return ["msvcr120"]

```

**Comment by ederwander** [comment] 2020-07-30 15:27
it worked ? I can close this issue ?

**Comment by GanerCodes** [comment] 2020-08-04 18:37
hey, sorry for being so late, had a busy week. 
It got further than last time but it errored again
![VUXWfG8](https://user-images.githubusercontent.com/34655998/89331593-a8295000-d657-11ea-8d15-8174ed48521c.png)

**Comment by ederwander** [comment] 2020-08-04 18:43
Well try replace

`return ["msvcr120"]` to  `return ["vcruntime140"] `

**Comment by GanerCodes** [comment] 2020-08-04 18:51
similar error.
also, have you considered setting up this project for PIP? It would make installing it a lot easier for everyone
![3x3MO5w](https://user-images.githubusercontent.com/34655998/89332769-9052cb80-d659-11ea-80d8-a4b514bc4ab6.png)

**Comment by ederwander** [comment] 2020-08-04 18:54
Wha is your last `msc_ver` in the file cygwinccompiler.py ??

**Comment by ederwander** [comment] 2020-08-04 18:58
Search `vcruntime140.dll` in your windows e copy it to` C:\Python37\libs` folder, try compile again .. and you will be happy lol

**Comment by GanerCodes** [comment] 2020-08-04 19:10
https://i.imgur.com/zUsx88K.png
https://i.imgur.com/wKtK1wf.png

**Comment by ederwander** [comment] 2020-08-04 19:30
hummm I think that you get the .dll for 32bits get the DLL 64bits in this folder  `C:\Windows\SysWOW64`

**Comment by GanerCodes** [comment] 2020-08-04 19:55
it changed a bit but still failed https://i.imgur.com/qJhK1Ic.png

**Comment by ederwander** [comment] 2020-08-04 19:59
This error is because your minGW is 32 bits and not 64bits

**Comment by GanerCodes** [comment] 2020-08-04 20:06
i installed the latest 64 bit version, and added the BIN folder to my path (https://i.imgur.com/nlORGOk.png) and it gave me these errors https://i.imgur.com/GmibWo5.png

**Comment by ederwander** [comment] 2020-08-04 20:09
wait a second you gcc not found the -lpython37 ...

**Comment by ederwander** [comment] 2020-08-04 20:34
well this error https://i.imgur.com/GmibWo5.png is why your gcc cant find the -python37 ...  your path and python installation seems a mess lol ...

Maybe it is the problem that you cant install pyaudio from pip

**Comment by ederwander** [comment] 2020-08-04 21:13
I install a clean python37 version and i can compile it again here, no problemmm

```
C:\msys64\mingw64\bin\gcc.exe -mdll -O -Wall -IC:\Python37\Lib\site-packages\numpy\core\include -Ic:\Python37\include -Ic:\Python37\include -c mayer_fft.c -o build\temp.win-amd64-3.7\Release\mayer_fft.o
writing build\temp.win-amd64-3.7\Release\AutoTune.cp37-win_amd64.def
C:\msys64\mingw64\bin\gcc.exe -shared -s build\temp.win-amd64-3.7\Release\pyautotuner.o build\temp.win-amd64-3.7\Release\autotalent.o build\temp.win-amd64-3.7\Release\mayer_fft.o build\temp.win-amd64-3.7\Release\AutoTune.cp37-win_amd64.def -Lc:\Python37\libs -Lc:\Python37\PCbuild\amd64 -lpython37 -lvcruntime140 -o build\lib.win-amd64-3.7\AutoTune.cp37-win_amd64.pyd
running install_lib
copying build\lib.win-amd64-3.7\AutoTune.cp37-win_amd64.pyd -> c:\Python37\Lib\site-packages
running install_egg_info
Removing c:\Python37\Lib\site-packages\PyAutoTune-0.1b-py3.7.egg-info
Writing c:\Python37\Lib\site-packages\PyAutoTune-0.1b-py3.7.egg-info
```

Take a look in my mingw, it is a pure 64 bits `C:\msys64\mingw64\bin\gcc.exe`  my vcruntime140 is a 64 bits too ...

**Comment by GanerCodes** [comment] 2020-08-04 21:22
it says it still cant find -lvcruntime140

**Comment by ederwander** [comment] 2020-08-04 21:30
How I said before you need find the `vcruntime140.dll`  64 bits in your windows and copy it to `C:\Python37\libs`

Its can work too using a `return ["msvcr120"]` in `cygwinccompiler.py`, find the `msvcr120.dll` 64 bits in your windows and copy to C:\Python37\libs

**Comment by GanerCodes** [comment] 2020-08-04 21:42
https://i.imgur.com/VZWTxF2.png
https://i.imgur.com/cjvCvWE.png
https://i.imgur.com/SIgslC1.png

**Comment by ederwander** [comment] 2020-08-04 22:00
you can see the error "incompatible" this file is 64bits ...

Try my .dll, download and copy to libs folder 

https://gofile.io/d/KG3IdH

**Comment by GanerCodes** [comment] 2020-08-04 22:58
did that, it gave me this https://i.imgur.com/hNELiS7.png

**Comment by ederwander** [comment] 2020-08-05 00:10
Nice ... congratulation you have compiled successfully

**Comment by GanerCodes** [comment] 2020-08-05 00:40
https://i.imgur.com/BPaLhfy.png

**Comment by ederwander** [comment] 2020-08-05 01:27
Autotune module was installed, now do you need install pyaudio

**Comment by ederwander** [comment] 2020-08-05 01:28
try pip install pyaudio

**Comment by GanerCodes** [comment] 2020-08-05 02:37
It finally works! Thank you!
Also, how do i:
1. Export it to a file
2. Use a song as a base to be autotuned to

**Comment by ederwander** [comment] 2020-08-08 00:41
This doubt is about how program?i not have time to code it for you, the first doubt   is very very easy to solve in python, maybe someone in the StackOverflow can show for you how to do what do you want ...

**Closed by ederwander** 2020-08-08 00:41 UTC

**Comment by GanerCodes** [comment] 2020-08-08 01:28
bruh, you could give me docs or at least lead me in the right direction

**Comment by ederwander** [comment] 2020-08-08 17:21
Well to save it to a file I write it for you, take a look [here](https://github.com/ederwander/PyAutoTune/blob/master/Examples/TuneAndSaveToFile.py) 

To use a song as a base, you need to extract all the pitch information from the base song and use it to change your voice, the current code changes the pitch based on the frequency table, and not based another tone song, to make this you will need to change the current C code a lot, I never saw docs that teach how to do it lol
